---
stages:
- name: Build
  inputs:
  - service: ${APP_REPO}
    type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    extension_id: ibm.devops.services.pipeline.maven.build.deploy
    SERVICE_INSTANCE: (default)
    BUILD_COMMAND: "#!/bin/bash\n# environment variables are available:\n# MAVEN_NAME:\
      \ name of the service instance\n# MAVEN_USER_ID: userid for the maven repository\n\
      # MAVEN_TOKEN: the token or password for the maven repository\n# MAVEN_SNAPSHOT_URL:\
      \ the maven snapshot repository\n# MAVEN_RELEASE_URL: the maven release repository\n\
      # MAVEN_MIRROR_URL: the maven mirror repository\n# The settings.xml is available\
      \ in /tmp/settings.xml\n# The name of the snapshots repository is 'snapshots'\n\
      # The name of the release repository is 'releases'\n# The name of the mirror\
      \ repository is 'central'\n\n\n\nmvn -s /tmp/settings.xml -B clean package \n"
    SERVICE_INSTANCE_TYPE: artifactory
- name: Test
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Unit tests
    type: tester
    script: |-
      #!/bin/bash

      #run unit tests that weren't run as part of the build
- name: Deploy [Dev]
  inputs:
  - type: job
    stage: Build
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash

      cf push "${CF_APP}" --hostname "${CF_APP}" -m 512M -p target/hello-world-1.0.0-SNAPSHOT.war
- name: System Test [DEV]
  inputs:
  - type: job
    stage: Build
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Test
    type: tester
    script: |-
      #!/bin/bash

      #curl something here
- name: Publish to Nexus
  inputs:
  - type: job
    stage: Build
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Publish
    type: builder
    extension_id: ibm.devops.services.pipeline.maven.build.deploy
    SERVICE_INSTANCE: (default)
    BUILD_COMMAND: |
      #!/bin/bash
      # environment variables are available:
      # MAVEN_NAME: name of the service instance
      # MAVEN_USER_ID: userid for the maven repository
      # MAVEN_TOKEN: the token or password for the maven repository
      # MAVEN_SNAPSHOT_URL: the maven snapshot repository
      # MAVEN_RELEASE_URL: the maven release repository
      # MAVEN_MIRROR_URL: the maven mirror repository
      # The settings.xml is available in /tmp/settings.xml
      # The name of the snapshots repository is 'snapshots'
      # The name of the release repository is 'releases'
      # The name of the mirror repository is 'central'


      mvn -s /tmp/settings.xml  \
      -DaltDeploymentRepository="snapshots::default::${MAVEN_SNAPSHOT_URL}" \
      deploy
    SERVICE_INSTANCE_TYPE: nexus
